import os

# stlport resolves the native C headers through NATIVE_C_INCLUDE and the C++
# wrappers through NATIVE_CPP_INCLUDE, both as a single flat directory.
# ReactOS has no such directory, so this generates one.  Each header is a
# one-line forwarder using an explicit SDK path macro, which keeps the real
# headers on the ordinary include path and avoids any chance of recursion.

C_HEADERS = {
    "assert.h": "CRT",
    "ctype.h": "CRT",
    "errno.h": "CRT",
    "float.h": "CRT",
    "limits.h": "VCRUNTIME",
    "locale.h": "CRT",
    "math.h": "CRT",
    "mem.h": "CRT",
    "setjmp.h": "VCRUNTIME",
    "signal.h": "CRT",
    "stdarg.h": "VCRUNTIME",
    "stddef.h": "CRT",
    "stdio.h": "CRT",
    "stdlib.h": "CRT",
    "string.h": "CRT",
    "time.h": "CRT",
    "wchar.h": "CRT",
    "wctype.h": "CRT",
}

# The C++ headers stlport may resolve.  ReactOS's sdk/include/c++ has most but
# not all of them, so every one is forwarded explicitly and the missing ones
# are supplied by the platform's own C headers.
CPP_HEADERS = {
    "cassert": None,
    "cctype": "ctype.h",
    "cerrno": "errno.h",
    "cfloat": None,
    "ciso646": None,
    "climits": "limits.h",
    "clocale": "locale.h",
    "cmath": None,
    "csetjmp": "setjmp.h",
    "csignal": "signal.h",
    "cstdarg": "stdarg.h",
    "cstddef": "stddef.h",
    "cstdio": "stdio.h",
    "cstdlib": "stdlib.h",
    "cstring": "string.h",
    "ctime": "time.h",
    "cwchar": "wchar.h",
    "cwctype": "wctype.h",
    "exception": None,
    "fstream": None,
    "ios": None,
    "iosfwd": None,
    "iostream": None,
    "istream": None,
    "limits": None,
    "new": None,
    "ostream": None,
    "sstream": None,
    "streambuf": None,
    "typeinfo": None,
}

HEADER = """/*
 * WinDosDX C++ compatibility header.
 *
 * DOSBox's machine core is built against ReactOS's stlport, which resolves the
 * native C and C++ headers through the NATIVE_C_INCLUDE and NATIVE_CPP_INCLUDE
 * macros as a single flat directory.  ReactOS has no such directory: its C
 * runtime headers are split across sdk/include/crt, sdk/include/ucrt and
 * sdk/include/vcruntime, and its C++ wrappers in sdk/include/c++ are an
 * incomplete set.
 *
 * This directory provides the flat view stlport expects.  Each header forwards
 * to the real one through an explicit path macro, so the actual headers stay
 * on the ordinary include path and nothing can recurse back here.
 *
 * Generated by windos_cxxcompat.py; see windos_core/CMakeLists.txt.
 */
#pragma once

#include {target}
"""

# ciso646 has no C equivalent; it is a no-op macro header.
CISO646 = """/*
 * WinDosDX C++ compatibility header.
 *
 * <ciso646> only defines alternative spellings of C++ keywords, all of which
 * the compiler already provides by default, so this is intentionally empty.
 *
 * Generated by windos_cxxcompat.py; see windos_core/CMakeLists.txt.
 */
#pragma once
"""

out = "base/applications/windos/windos_core/src/dosbox/cxxcompat"
os.makedirs(out, exist_ok=True)

for name, where in sorted(C_HEADERS.items()):
    with open(os.path.join(out, name), "w", newline="\n") as fp:
        fp.write(HEADER.format(target="WINDOS_SDK_%s/%s" % (where, name)))

for name, c_equiv in sorted(CPP_HEADERS.items()):
    with open(os.path.join(out, name), "w", newline="\n") as fp:
        if name == "ciso646":
            fp.write(CISO646)
        elif c_equiv:
            fp.write(HEADER.format(target="<%s>" % c_equiv))
        else:
            fp.write(HEADER.format(target="WINDOS_SDK_CXX/%s" % name))

print("generated %d headers in %s" % (len(C_HEADERS) + len(CPP_HEADERS), out))
