/*
 * WinDosDX C++ compatibility header.
 *
 * DOSBox's machine core is built against ReactOS's stlport, which resolves the
 * native C and C++ headers through the NATIVE_C_INCLUDE and NATIVE_CPP_INCLUDE
 * macros as a single flat directory.  ReactOS has no such directory: its C
 * runtime headers are split across sdk/include/crt, sdk/include/ucrt and
 * sdk/include/vcruntime, and its C++ wrappers in sdk/include/c++ are an
 * incomplete set.
 *
 * This directory provides the flat view stlport expects.  Each header forwards
 * to the real one through an explicit path macro, so the actual headers stay
 * on the ordinary include path and nothing can recurse back here.
 *
 * Generated by windos_cxxcompat.py; see windos_core/CMakeLists.txt.
 */
#pragma once

#include WINDOS_SDK_CRT/time.h
